// Generated by scripts/generate-collections.mjs from public/images/collection. Do not edit by hand.
import type { StaticImageData } from "next/image";

import alanya0 from "../../public/images/collection/alanya/2639-4.jpg";
import alanya1 from "../../public/images/collection/alanya/2640-1.jpg";
import alanya2 from "../../public/images/collection/alanya/2641-2.jpg";
import alanya3 from "../../public/images/collection/alanya/6062-7.jpg";
import alanya4 from "../../public/images/collection/alanya/29053-6.jpg";
import alanya5 from "../../public/images/collection/alanya/29053-7.jpg";
import alanya6 from "../../public/images/collection/alanya/29100-5.jpg";
import alanya7 from "../../public/images/collection/alanya/29102-6.jpg";
import alanya8 from "../../public/images/collection/alanya/29140-5.jpg";
import alanya9 from "../../public/images/collection/alanya/29149-2.jpg";
import alanya10 from "../../public/images/collection/alanya/29150-4.jpg";
import bursa0 from "../../public/images/collection/bursa/189-09.jpg";
import bursa1 from "../../public/images/collection/bursa/319-04.jpg";
import bursa2 from "../../public/images/collection/bursa/319-06.jpg";
import bursa3 from "../../public/images/collection/bursa/319-09.jpg";
import bursa4 from "../../public/images/collection/bursa/340-07.jpg";
import bursa5 from "../../public/images/collection/bursa/354-07.jpg";
import bursa6 from "../../public/images/collection/bursa/437-03.jpg";
import bursa7 from "../../public/images/collection/bursa/437-05.jpg";
import bursa8 from "../../public/images/collection/bursa/437-08.jpg";
import bursa9 from "../../public/images/collection/bursa/2002-3.jpg";
import bursa10 from "../../public/images/collection/bursa/2002-5.jpg";
import bursa11 from "../../public/images/collection/bursa/2002-6.jpg";
import bursa12 from "../../public/images/collection/bursa/2614-7.jpg";
import bursa13 from "../../public/images/collection/bursa/2624-1.jpg";
import bursa14 from "../../public/images/collection/bursa/19005-6.jpg";
import bursa15 from "../../public/images/collection/bursa/19027-4.jpg";
import bursa16 from "../../public/images/collection/bursa/19027-5.jpg";
import bursa17 from "../../public/images/collection/bursa/23011-1.jpg";
import bursa18 from "../../public/images/collection/bursa/29034-18.jpg";
import bursa19 from "../../public/images/collection/bursa/29036-11.jpg";
import bursa20 from "../../public/images/collection/bursa/29045-8.jpg";
import bursa21 from "../../public/images/collection/bursa/29050-3.jpg";
import bursa22 from "../../public/images/collection/bursa/29098-04.jpg";
import bursa23 from "../../public/images/collection/bursa/29098-11.jpg";
import bursa24 from "../../public/images/collection/bursa/29100-4.jpg";
import bursa25 from "../../public/images/collection/bursa/81150-3.jpg";
import denver0 from "../../public/images/collection/denver/0004-3.jpg";
import denver1 from "../../public/images/collection/denver/189-09.jpg";
import denver2 from "../../public/images/collection/denver/354-07.jpg";
import denver3 from "../../public/images/collection/denver/1294-1.jpg";
import denver4 from "../../public/images/collection/denver/1294-5.jpg";
import denver5 from "../../public/images/collection/denver/1294-6.jpg";
import denver6 from "../../public/images/collection/denver/7310-14.jpg";
import denver7 from "../../public/images/collection/denver/7310-18.jpg";
import denver8 from "../../public/images/collection/denver/7324-1.jpg";
import denver9 from "../../public/images/collection/denver/7324-8.jpg";
import denver10 from "../../public/images/collection/denver/16011-2.jpg";
import denver11 from "../../public/images/collection/denver/16011-7.jpg";
import denver12 from "../../public/images/collection/denver/16011-8.jpg";
import denver13 from "../../public/images/collection/denver/29032-1.jpg";
import denver14 from "../../public/images/collection/denver/29034-18.jpg";
import denver15 from "../../public/images/collection/denver/29045-1.jpg";
import denver16 from "../../public/images/collection/denver/29140-3.jpg";
import denver17 from "../../public/images/collection/denver/29140-7.jpg";
import denver18 from "../../public/images/collection/denver/29167A-8.jpg";
import denver19 from "../../public/images/collection/denver/29167B-5.jpg";
import denver20 from "../../public/images/collection/denver/29167B-8.jpg";
import denver21 from "../../public/images/collection/denver/29167B-14.jpg";
import denver22 from "../../public/images/collection/denver/29167B-19.jpg";
import denver23 from "../../public/images/collection/denver/fc7310-18.jpg";
import denver24 from "../../public/images/collection/denver/TR4488.jpg";
import florence0 from "../../public/images/collection/florence/189-10.jpg";
import florence1 from "../../public/images/collection/florence/2602-1.jpg";
import florence2 from "../../public/images/collection/florence/2602-2.jpg";
import florence3 from "../../public/images/collection/florence/2641-3.jpg";
import florence4 from "../../public/images/collection/florence/6070-6.jpg";
import florence5 from "../../public/images/collection/florence/29074-1.jpg";
import florence6 from "../../public/images/collection/florence/29098-99.jpg";
import florence7 from "../../public/images/collection/florence/29149-7.jpg";
import florence8 from "../../public/images/collection/florence/29150-3.jpg";
import florence9 from "../../public/images/collection/florence/29150-6.jpg";
import muskoka0 from "../../public/images/collection/muskoka/2614-1.jpg";
import muskoka1 from "../../public/images/collection/muskoka/2639-5.jpg";
import muskoka2 from "../../public/images/collection/muskoka/6079-3.jpg";
import muskoka3 from "../../public/images/collection/muskoka/29039-8.jpg";
import muskoka4 from "../../public/images/collection/muskoka/29052-5.jpg";
import muskoka5 from "../../public/images/collection/muskoka/29098-2.jpg";
import muskoka6 from "../../public/images/collection/muskoka/29100-8.jpg";
import muskoka7 from "../../public/images/collection/muskoka/29101-6.jpg";
import muskoka8 from "../../public/images/collection/muskoka/29145-1.jpg";
import muskoka9 from "../../public/images/collection/muskoka/29150-1.jpg";
import muskoka10 from "../../public/images/collection/muskoka/29151-3.jpg";
import muskoka11 from "../../public/images/collection/muskoka/29151-3(D).jpg";
import muskoka12 from "../../public/images/collection/muskoka/29151-3(d1).jpg";
import ontario0 from "../../public/images/collection/ontario/189-07.jpg";
import ontario1 from "../../public/images/collection/ontario/319-09.jpg";
import ontario2 from "../../public/images/collection/ontario/340-06.jpg";
import ontario3 from "../../public/images/collection/ontario/19018-11.jpg";
import ontario4 from "../../public/images/collection/ontario/19020-7.jpg";
import ontario5 from "../../public/images/collection/ontario/19022-5.jpg";
import ontario6 from "../../public/images/collection/ontario/29034-3.jpg";
import ontario7 from "../../public/images/collection/ontario/29036-11.jpg";
import ontario8 from "../../public/images/collection/ontario/29050-3.jpg";
import ontario9 from "../../public/images/collection/ontario/29053-3.jpg";
import ontario10 from "../../public/images/collection/ontario/29053-4.jpg";
import ontario11 from "../../public/images/collection/ontario/29053-8.jpg";
import ontario12 from "../../public/images/collection/ontario/29098-4.jpg";
import ontario13 from "../../public/images/collection/ontario/29100-4.jpg";
import ontario14 from "../../public/images/collection/ontario/29115-9.jpg";
import ontario15 from "../../public/images/collection/ontario/29123-1.jpg";
import ontario16 from "../../public/images/collection/ontario/29123-3.jpg";
import ontario17 from "../../public/images/collection/ontario/29148-4.jpg";
import ontario18 from "../../public/images/collection/ontario/29148-5.jpg";
import ontario19 from "../../public/images/collection/ontario/29163-1.jpg";
import ontario20 from "../../public/images/collection/ontario/29185L-2.jpg";
import ontario21 from "../../public/images/collection/ontario/OM1581-09.jpg";
import sofia0 from "../../public/images/collection/sofia/0005-3.jpg";
import sofia1 from "../../public/images/collection/sofia/319-04.jpg";
import sofia2 from "../../public/images/collection/sofia/333-05.jpg";
import sofia3 from "../../public/images/collection/sofia/340-03.jpg";
import sofia4 from "../../public/images/collection/sofia/413-02.jpg";
import sofia5 from "../../public/images/collection/sofia/1001-3.jpg";
import sofia6 from "../../public/images/collection/sofia/7237.jpg";
import sofia7 from "../../public/images/collection/sofia/7265-7.jpg";
import sofia8 from "../../public/images/collection/sofia/7322-45.jpg";
import sofia9 from "../../public/images/collection/sofia/16007-2.jpg";
import sofia10 from "../../public/images/collection/sofia/19005-2.jpg";
import sofia11 from "../../public/images/collection/sofia/19017-13.jpg";
import sofia12 from "../../public/images/collection/sofia/29036-1.jpg";
import sofia13 from "../../public/images/collection/sofia/29036-2.jpg";
import sofia14 from "../../public/images/collection/sofia/29036-5.jpg";
import sofia15 from "../../public/images/collection/sofia/29036-6.jpg";
import sofia16 from "../../public/images/collection/sofia/29036-15.jpg";
import sofia17 from "../../public/images/collection/sofia/29043-3.jpg";
import sofia18 from "../../public/images/collection/sofia/29053-1.jpg";
import sofia19 from "../../public/images/collection/sofia/29070-3.jpg";
import sofia20 from "../../public/images/collection/sofia/29115-18.jpg";
import sofia21 from "../../public/images/collection/sofia/29148-2.jpg";
import sofia22 from "../../public/images/collection/sofia/29148-3.jpg";
import sofia23 from "../../public/images/collection/sofia/29163-7.jpg";
import sofia24 from "../../public/images/collection/sofia/JC6151-3.jpg";
import sofia25 from "../../public/images/collection/sofia/tcm341-2.jpg";

/** A decor photo of a collection. The code is the file name, shown as is in every language. */
export type CollectionPhoto = { code: string; src: StaticImageData };

export const collections = {
  alanya: [
    { code: "2639-4", src: alanya0 },
    { code: "2640-1", src: alanya1 },
    { code: "2641-2", src: alanya2 },
    { code: "6062-7", src: alanya3 },
    { code: "29053-6", src: alanya4 },
    { code: "29053-7", src: alanya5 },
    { code: "29100-5", src: alanya6 },
    { code: "29102-6", src: alanya7 },
    { code: "29140-5", src: alanya8 },
    { code: "29149-2", src: alanya9 },
    { code: "29150-4", src: alanya10 },
  ],
  bursa: [
    { code: "189-09", src: bursa0 },
    { code: "319-04", src: bursa1 },
    { code: "319-06", src: bursa2 },
    { code: "319-09", src: bursa3 },
    { code: "340-07", src: bursa4 },
    { code: "354-07", src: bursa5 },
    { code: "437-03", src: bursa6 },
    { code: "437-05", src: bursa7 },
    { code: "437-08", src: bursa8 },
    { code: "2002-3", src: bursa9 },
    { code: "2002-5", src: bursa10 },
    { code: "2002-6", src: bursa11 },
    { code: "2614-7", src: bursa12 },
    { code: "2624-1", src: bursa13 },
    { code: "19005-6", src: bursa14 },
    { code: "19027-4", src: bursa15 },
    { code: "19027-5", src: bursa16 },
    { code: "23011-1", src: bursa17 },
    { code: "29034-18", src: bursa18 },
    { code: "29036-11", src: bursa19 },
    { code: "29045-8", src: bursa20 },
    { code: "29050-3", src: bursa21 },
    { code: "29098-04", src: bursa22 },
    { code: "29098-11", src: bursa23 },
    { code: "29100-4", src: bursa24 },
    { code: "81150-3", src: bursa25 },
  ],
  denver: [
    { code: "0004-3", src: denver0 },
    { code: "189-09", src: denver1 },
    { code: "354-07", src: denver2 },
    { code: "1294-1", src: denver3 },
    { code: "1294-5", src: denver4 },
    { code: "1294-6", src: denver5 },
    { code: "7310-14", src: denver6 },
    { code: "7310-18", src: denver7 },
    { code: "7324-1", src: denver8 },
    { code: "7324-8", src: denver9 },
    { code: "16011-2", src: denver10 },
    { code: "16011-7", src: denver11 },
    { code: "16011-8", src: denver12 },
    { code: "29032-1", src: denver13 },
    { code: "29034-18", src: denver14 },
    { code: "29045-1", src: denver15 },
    { code: "29140-3", src: denver16 },
    { code: "29140-7", src: denver17 },
    { code: "29167A-8", src: denver18 },
    { code: "29167B-5", src: denver19 },
    { code: "29167B-8", src: denver20 },
    { code: "29167B-14", src: denver21 },
    { code: "29167B-19", src: denver22 },
    { code: "fc7310-18", src: denver23 },
    { code: "TR4488", src: denver24 },
  ],
  florence: [
    { code: "189-10", src: florence0 },
    { code: "2602-1", src: florence1 },
    { code: "2602-2", src: florence2 },
    { code: "2641-3", src: florence3 },
    { code: "6070-6", src: florence4 },
    { code: "29074-1", src: florence5 },
    { code: "29098-99", src: florence6 },
    { code: "29149-7", src: florence7 },
    { code: "29150-3", src: florence8 },
    { code: "29150-6", src: florence9 },
  ],
  muskoka: [
    { code: "2614-1", src: muskoka0 },
    { code: "2639-5", src: muskoka1 },
    { code: "6079-3", src: muskoka2 },
    { code: "29039-8", src: muskoka3 },
    { code: "29052-5", src: muskoka4 },
    { code: "29098-2", src: muskoka5 },
    { code: "29100-8", src: muskoka6 },
    { code: "29101-6", src: muskoka7 },
    { code: "29145-1", src: muskoka8 },
    { code: "29150-1", src: muskoka9 },
    { code: "29151-3", src: muskoka10 },
    { code: "29151-3(D)", src: muskoka11 },
    { code: "29151-3(d1)", src: muskoka12 },
  ],
  ontario: [
    { code: "189-07", src: ontario0 },
    { code: "319-09", src: ontario1 },
    { code: "340-06", src: ontario2 },
    { code: "19018-11", src: ontario3 },
    { code: "19020-7", src: ontario4 },
    { code: "19022-5", src: ontario5 },
    { code: "29034-3", src: ontario6 },
    { code: "29036-11", src: ontario7 },
    { code: "29050-3", src: ontario8 },
    { code: "29053-3", src: ontario9 },
    { code: "29053-4", src: ontario10 },
    { code: "29053-8", src: ontario11 },
    { code: "29098-4", src: ontario12 },
    { code: "29100-4", src: ontario13 },
    { code: "29115-9", src: ontario14 },
    { code: "29123-1", src: ontario15 },
    { code: "29123-3", src: ontario16 },
    { code: "29148-4", src: ontario17 },
    { code: "29148-5", src: ontario18 },
    { code: "29163-1", src: ontario19 },
    { code: "29185L-2", src: ontario20 },
    { code: "OM1581-09", src: ontario21 },
  ],
  sofia: [
    { code: "0005-3", src: sofia0 },
    { code: "319-04", src: sofia1 },
    { code: "333-05", src: sofia2 },
    { code: "340-03", src: sofia3 },
    { code: "413-02", src: sofia4 },
    { code: "1001-3", src: sofia5 },
    { code: "7237", src: sofia6 },
    { code: "7265-7", src: sofia7 },
    { code: "7322-45", src: sofia8 },
    { code: "16007-2", src: sofia9 },
    { code: "19005-2", src: sofia10 },
    { code: "19017-13", src: sofia11 },
    { code: "29036-1", src: sofia12 },
    { code: "29036-2", src: sofia13 },
    { code: "29036-5", src: sofia14 },
    { code: "29036-6", src: sofia15 },
    { code: "29036-15", src: sofia16 },
    { code: "29043-3", src: sofia17 },
    { code: "29053-1", src: sofia18 },
    { code: "29070-3", src: sofia19 },
    { code: "29115-18", src: sofia20 },
    { code: "29148-2", src: sofia21 },
    { code: "29148-3", src: sofia22 },
    { code: "29163-7", src: sofia23 },
    { code: "JC6151-3", src: sofia24 },
    { code: "tcm341-2", src: sofia25 },
  ],
} satisfies Record<string, CollectionPhoto[]>;

export type CollectionId = keyof typeof collections;
